### PR TITLE
Fix publish_dir name and update gh-pages actions

### LINKED ISSUE #4: JavaDocs workflow not working
Likely due to updating the JavaDocs Maven Plugin version

Nothing is getting pushed to the gh-pages branch.

Looking at the output of the CI, the JavaDocs is getting published to:

```
Generating /home/runner/work/spdx-java-v3jsonld-store/spdx-java-v3jsonld-store/target/reports/apidocs/help-doc.html...
```

### PR DESCRIPTION
**Pull request by bact**
- Fix publish_dir name (`report` -> `reports`)
- Update peaceiris/actions-gh-pages to v4
- Update `source` config of maven-javadoc-plugin in pom.xml to match `java-version` (11) in docs.yml
- Will fix #4
- See demo here: https://bact.github.io/spdx-java-v3jsonld-store/

----

Note that there are these 100 warnings (since before this PR, and this PR does not fix that yet):

> Warning: [WARNING] javadoc: warning - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

(See [Generate docs](https://github.com/spdx/spdx-java-v3jsonld-store/actions/runs/12362717762/job/34502607077) step in one of the runs)

They occure as Javadoc reports that some code use ["modules" (JPMS)](https://www.oracle.com/ie/corporate/features/understanding-java-9-modules.html) which is not yet supported in Java 8.

Changing `source` and `target` of maven-compiler-plugin in pom.xml to `9` or later will fix those warnings.

### CODE REVIEW

**Review by goneall — CHANGES_REQUESTED** [review]
Thanks @bact :)  I was trying to figure out why the javadocs wasn't working.

Why don't you go ahead and change the source and target of maven-compiler-plugin in pom.xml to 9 in this PR to fix the warnings.

**Comment by bact** [comment]
@goneall maven-compiler-plugin source/target are now updated to 9

**Comment by bact** [comment]
@goneall I think I messed up with commits. Let me fix those first.

**Comment by bact** [comment]
I will close this one and open another clean PR.

**Comment by bact** [comment]
Please use PR #10 instead.

**Pull request closed without merging**
